Conjunto: ./src/Conjunto.hpp ./src/Conjunto.cpp ./src/funciones.hpp ./src/funciones.cpp ./src/main.cpp
	g++  -o ./built/Conjunto.out ./src/Conjunto.cpp ./src/funciones.cpp  ./src/main.cpp 

clean:
	rm ./built/*